/**
 * LEXORA instructional word bank — Filipino (Tagalog), sequenced by the
 * Marungko Approach.
 *
 * Each entry is [text, syllables, pattern, level, meaningEn]. The Marungko
 * stage is NOT listed: it is derived from the letters in the word, so a word
 * can never be shown before every letter in it has been taught.
 *
 * Difficulty levels
 *   1  two-syllable words with open syllables (CV-CV, V-CV)
 *   2  a closed syllable or a vowel sequence
 *   3  three syllables
 *   4  consonant clusters or complex codas
 *   5  four or more syllables
 *
 * Depth matters as much as breadth here. An exercise draws eight items, so a
 * level holding only eight words would serve the identical set every session
 * and a learner could memorise it instead of decoding. Aim for at least ~25
 * words per level; `npm run words:check` reports the spread.
 */
export type WordEntry = [
  text: string,
  syllables: string,
  pattern: string,
  level: number,
  meaningEn: string,
];

export const WORDS: WordEntry[] = [
  /* ── Level 1 — two open syllables ─────────────────────────────────────── */
  ["ama", "a-ma", "VCV", 1, "father"],
  ["mama", "ma-ma", "CVCV", 1, "mom"],
  ["masa", "ma-sa", "CVCV", 1, "dough"],
  ["sama", "sa-ma", "CVCV", 1, "to join"],
  ["asa", "a-sa", "VCV", 1, "to hope"],
  ["aso", "a-so", "VCV", 1, "dog"],
  ["oso", "o-so", "VCV", 1, "bear"],
  ["isa", "i-sa", "VCV", 1, "one"],
  ["misa", "mi-sa", "CVCV", 1, "mass (church)"],
  ["sisi", "si-si", "CVCV", 1, "blame"],
  ["amo", "a-mo", "VCV", 1, "boss"],
  ["abo", "a-bo", "VCV", 1, "ash"],
  ["ube", "u-be", "VCV", 1, "purple yam"],
  ["ubo", "u-bo", "VCV", 1, "cough"],
  ["iba", "i-ba", "VCV", 1, "other"],
  ["baso", "ba-so", "CVCV", 1, "drinking glass"],
  ["mesa", "me-sa", "CVCV", 1, "table"],
  ["bibe", "bi-be", "CVCV", 1, "duckling"],
  ["baba", "ba-ba", "CVCV", 1, "chin"],
  ["sabi", "sa-bi", "CVCV", 1, "said"],
  ["basa", "ba-sa", "CVCV", 1, "wet; to read"],
  ["bisa", "bi-sa", "CVCV", 1, "effect"],
  ["lata", "la-ta", "CVCV", 1, "tin can"],
  ["bola", "bo-la", "CVCV", 1, "ball"],
  ["tela", "te-la", "CVCV", 1, "cloth"],
  ["bato", "ba-to", "CVCV", 1, "stone"],
  ["tubo", "tu-bo", "CVCV", 1, "pipe; sugarcane"],
  ["talo", "ta-lo", "CVCV", 1, "defeated"],
  ["kuto", "ku-to", "CVCV", 1, "head louse"],
  ["tasa", "ta-sa", "CVCV", 1, "cup"],
  ["lobo", "lo-bo", "CVCV", 1, "balloon"],
  ["buko", "bu-ko", "CVCV", 1, "young coconut"],
  ["mata", "ma-ta", "CVCV", 1, "eye"],
  ["bata", "ba-ta", "CVCV", 1, "child"],
  ["sala", "sa-la", "CVCV", 1, "living room"],
  ["tali", "ta-li", "CVCV", 1, "rope"],
  ["bote", "bo-te", "CVCV", 1, "bottle"],
  ["kuko", "ku-ko", "CVCV", 1, "fingernail"],
  ["suso", "su-so", "CVCV", 1, "snail"],
  ["tuko", "tu-ko", "CVCV", 1, "gecko"],
  ["kilo", "ki-lo", "CVCV", 1, "kilo"],
  ["lola", "lo-la", "CVCV", 1, "grandmother"],
  ["lolo", "lo-lo", "CVCV", 1, "grandfather"],
  ["ate", "a-te", "VCV", 1, "older sister"],
  ["gabi", "ga-bi", "CVCV", 1, "night; taro"],
  ["yelo", "ye-lo", "CVCV", 1, "ice"],
  ["yaya", "ya-ya", "CVCV", 1, "nanny"],
  ["mani", "ma-ni", "CVCV", 1, "peanut"],
  ["ina", "i-na", "VCV", 1, "mother"],
  ["tiya", "ti-ya", "CVCV", 1, "aunt"],
  ["kuya", "ku-ya", "CVCV", 1, "older brother"],
  ["yema", "ye-ma", "CVCV", 1, "egg yolk"],
  ["puno", "pu-no", "CVCV", 1, "tree"],
  ["pera", "pe-ra", "CVCV", 1, "money"],
  ["pusa", "pu-sa", "CVCV", 1, "cat"],
  ["puso", "pu-so", "CVCV", 1, "heart"],
  ["dila", "di-la", "CVCV", 1, "tongue"],
  ["daga", "da-ga", "CVCV", 1, "mouse"],
  ["damo", "da-mo", "CVCV", 1, "grass"],
  ["relo", "re-lo", "CVCV", 1, "watch"],
  ["wika", "wi-ka", "CVCV", 1, "language"],
  ["pito", "pi-to", "CVCV", 1, "whistle; seven"],
  ["hita", "hi-ta", "CVCV", 1, "thigh"],
  ["hari", "ha-ri", "CVCV", 1, "king"],
  ["puto", "pu-to", "CVCV", 1, "rice cake"],
  ["pako", "pa-ko", "CVCV", 1, "nail"],
  ["sipa", "si-pa", "CVCV", 1, "kick"],
  ["dito", "di-to", "CVCV", 1, "here"],
  ["hilo", "hi-lo", "CVCV", 1, "dizzy"],
  ["sapa", "sa-pa", "CVCV", 1, "creek"],
  ["para", "pa-ra", "CVCV", 1, "for; stop"],
  ["wala", "wa-la", "CVCV", 1, "none; nothing"],

  /* ── Level 2 — a closed syllable or vowel sequence ────────────────────── */
  ["mas", "mas", "CVC", 2, "more"],
  ["mais", "ma-is", "CVVC", 2, "corn"],
  ["asim", "a-sim", "VCVC", 2, "sourness"],
  ["ubas", "u-bas", "VCVC", 2, "grapes"],
  ["bus", "bus", "CVC", 2, "bus"],
  ["buo", "bu-o", "CVV", 2, "whole"],
  ["bao", "ba-o", "CVV", 2, "coconut shell"],
  ["sulat", "su-lat", "CVCVC", 2, "letter; to write"],
  ["takot", "ta-kot", "CVCVC", 2, "fear"],
  ["bukas", "bu-kas", "CVCVC", 2, "tomorrow; open"],
  ["bakal", "ba-kal", "CVCVC", 2, "steel"],
  ["lakas", "la-kas", "CVCVC", 2, "strength"],
  ["sakit", "sa-kit", "CVCVC", 2, "pain"],
  ["lamok", "la-mok", "CVCVC", 2, "mosquito"],
  ["kamot", "ka-mot", "CVCVC", 2, "scratch"],
  ["tulak", "tu-lak", "CVCVC", 2, "push"],
  ["malas", "ma-las", "CVCVC", 2, "bad luck"],
  ["kulot", "ku-lot", "CVCVC", 2, "curly"],
  ["sabit", "sa-bit", "CVCVC", 2, "to hang"],
  ["kabit", "ka-bit", "CVCVC", 2, "to attach"],
  ["labas", "la-bas", "CVCVC", 2, "outside"],
  ["loob", "lo-ob", "CVVC", 2, "inside"],
  ["isip", "i-sip", "VCVC", 2, "mind"],
  ["atis", "a-tis", "VCVC", 2, "sugar apple"],
  ["nanay", "na-nay", "CVCVC", 2, "mother"],
  ["tatay", "ta-tay", "CVCVC", 2, "father"],
  ["gulay", "gu-lay", "CVCVC", 2, "vegetable"],
  ["gatas", "ga-tas", "CVCVC", 2, "milk"],
  ["bunso", "bun-so", "CVCCV", 2, "youngest child"],
  ["niyog", "ni-yog", "CVCVC", 2, "coconut"],
  ["bantay", "ban-tay", "CVCCVC", 2, "guard"],
  ["itlog", "it-log", "VCCVC", 2, "egg"],
  ["ulan", "u-lan", "VCVC", 2, "rain"],
  ["ilog", "i-log", "VCVC", 2, "river"],
  ["kanin", "ka-nin", "CVCVC", 2, "cooked rice"],
  ["gamit", "ga-mit", "CVCVC", 2, "thing; to use"],
  ["buntis", "bun-tis", "CVCCVC", 2, "pregnant"],
  ["sinag", "si-nag", "CVCVC", 2, "ray of light"],
  ["tinig", "ti-nig", "CVCVC", 2, "voice"],
  ["manok", "ma-nok", "CVCVC", 2, "chicken"],
  ["sanay", "sa-nay", "CVCVC", 2, "accustomed"],
  ["yaman", "ya-man", "CVCVC", 2, "wealth"],
  ["buntot", "bun-tot", "CVCCVC", 2, "tail"],
  ["kanan", "ka-nan", "CVCVC", 2, "right side"],
  ["damit", "da-mit", "CVCVC", 2, "clothes"],
  ["dahon", "da-hon", "CVCVC", 2, "leaf"],
  ["bahay", "ba-hay", "CVCVC", 2, "house"],
  ["buhay", "bu-hay", "CVCVC", 2, "life"],
  ["araw", "a-raw", "VCVC", 2, "sun; day"],
  ["ilaw", "i-law", "VCVC", 2, "light"],
  ["ulap", "u-lap", "VCVC", 2, "cloud"],
  ["hipon", "hi-pon", "CVCVC", 2, "shrimp"],
  ["hilaw", "hi-law", "CVCVC", 2, "unripe"],
  ["isda", "is-da", "VCCV", 2, "fish"],
  ["pinto", "pin-to", "CVCCV", 2, "door"],
  ["radyo", "rad-yo", "CVCCV", 2, "radio"],
  ["hardin", "har-din", "CVCCVC", 2, "garden"],
  ["sampay", "sam-pay", "CVCCVC", 2, "hung laundry"],
  ["lapis", "la-pis", "CVCVC", 2, "pencil"],
  ["palad", "pa-lad", "CVCVC", 2, "palm of the hand"],
  ["dagat", "da-gat", "CVCVC", 2, "sea"],
  ["hapon", "ha-pon", "CVCVC", 2, "afternoon"],
  ["putik", "pu-tik", "CVCVC", 2, "mud"],
  ["silid", "si-lid", "CVCVC", 2, "room"],
  ["sabaw", "sa-baw", "CVCVC", 2, "soup"],
  ["kahoy", "ka-hoy", "CVCVC", 2, "wood"],
  ["sipon", "si-pon", "CVCVC", 2, "runny nose"],
  ["bakod", "ba-kod", "CVCVC", 2, "fence"],
  ["pusod", "pu-sod", "CVCVC", 2, "navel"],
  ["dilaw", "di-law", "CVCVC", 2, "yellow"],
  ["pulot", "pu-lot", "CVCVC", 2, "honey"],
  ["duyan", "du-yan", "CVCVC", 2, "hammock"],
  ["paa", "pa-a", "CVV", 2, "foot"],

  /* ── Level 3 — three syllables ────────────────────────────────────────── */
  ["bumasa", "bu-ma-sa", "CVCVCV", 3, "to read"],
  ["babae", "ba-ba-e", "CVCVV", 3, "woman"],
  ["salamat", "sa-la-mat", "CVCVCVC", 3, "thank you"],
  ["kamatis", "ka-ma-tis", "CVCVCVC", 3, "tomato"],
  ["makulit", "ma-ku-lit", "CVCVCVC", 3, "persistent"],
  ["kulambo", "ku-lam-bo", "CVCVCCV", 3, "mosquito net"],
  ["matamis", "ma-ta-mis", "CVCVCVC", 3, "sweet"],
  ["mabilis", "ma-bi-lis", "CVCVCVC", 3, "fast"],
  ["bumili", "bu-mi-li", "CVCVCV", 3, "to buy"],
  ["tumakbo", "tu-mak-bo", "CVCVCCV", 3, "ran"],
  ["malakas", "ma-la-kas", "CVCVCVC", 3, "strong"],
  ["masakit", "ma-sa-kit", "CVCVCVC", 3, "painful"],
  ["salamin", "sa-la-min", "CVCVCVC", 3, "mirror; eyeglasses"],
  ["nilaga", "ni-la-ga", "CVCVCV", 3, "boiled dish"],
  ["malinis", "ma-li-nis", "CVCVCVC", 3, "clean"],
  ["maligo", "ma-li-go", "CVCVCV", 3, "to bathe"],
  ["binata", "bi-na-ta", "CVCVCV", 3, "young man"],
  ["malamig", "ma-la-mig", "CVCVCVC", 3, "cold"],
  ["watawat", "wa-ta-wat", "CVCVCVC", 3, "flag"],
  ["tinapay", "ti-na-pay", "CVCVCVC", 3, "bread"],
  ["kandila", "kan-di-la", "CVCCVCV", 3, "candle"],
  ["diwata", "di-wa-ta", "CVCVCV", 3, "fairy"],
  ["payaso", "pa-ya-so", "CVCVCV", 3, "clown"],
  ["sapatos", "sa-pa-tos", "CVCVCVC", 3, "shoes"],
  ["mapula", "ma-pu-la", "CVCVCV", 3, "red"],
  ["malapit", "ma-la-pit", "CVCVCVC", 3, "near"],
  ["bituin", "bi-tu-in", "CVCVVC", 3, "star"],
  ["paniki", "pa-ni-ki", "CVCVCV", 3, "bat"],
  ["tahimik", "ta-hi-mik", "CVCVCVC", 3, "quiet"],
  ["malusog", "ma-lu-sog", "CVCVCVC", 3, "healthy"],
  ["mabuhay", "ma-bu-hay", "CVCVCVC", 3, "long live"],
  ["damdamin", "dam-da-min", "CVCCVCVC", 3, "feeling"],
  ["ngipin", "ngi-pin", "CVCVC(ng)", 3, "tooth"],
  ["ngiti", "ngi-ti", "CVCV(ng)", 3, "smile"],
  ["ngayon", "nga-yon", "CVCVC(ng)", 3, "now; today"],
  ["saging", "sa-ging", "CVCVC(ng)", 3, "banana"],
  ["payong", "pa-yong", "CVCVC(ng)", 3, "umbrella"],
  ["gunting", "gun-ting", "CVCCVC(ng)", 3, "scissors"],
  ["mangga", "mang-ga", "CVCCV(ng)", 3, "mango"],
  ["bangka", "bang-ka", "CVCCV(ng)", 3, "boat"],
  ["bangus", "ba-ngus", "CVCVC(ng)", 3, "milkfish"],
  ["tulong", "tu-long", "CVCVC(ng)", 3, "help"],
  ["gulong", "gu-long", "CVCVC(ng)", 3, "wheel"],
  ["hangin", "ha-ngin", "CVCVC(ng)", 3, "wind"],
  ["langit", "la-ngit", "CVCVC(ng)", 3, "sky"],
  ["singsing", "sing-sing", "CVCCVC(ng)", 3, "ring"],
  ["lungsod", "lung-sod", "CVCCVC(ng)", 3, "city"],
  ["sungay", "su-ngay", "CVCVC(ng)", 3, "horn"],
  ["bunga", "bu-nga", "CVCV(ng)", 3, "fruit"],
  ["bango", "ba-ngo", "CVCV(ng)", 3, "scent"],
  ["linggo", "ling-go", "CVCCV(ng)", 3, "week; Sunday"],
  ["sinigang", "si-ni-gang", "CVCVCVC(ng)", 3, "sour soup"],
  ["kotse", "kot-se", "CVCCV", 3, "car"],
  ["tunog", "tu-nog", "CVCVC", 3, "sound"],

  /* ── Level 4 — consonant clusters and complex codas ───────────────────── */
  ["aklat", "ak-lat", "VCCVC", 4, "book"],
  ["bulaklak", "bu-lak-lak", "CVCVCCVC", 4, "flower"],
  ["klase", "kla-se", "CCVCV", 4, "class"],
  ["blusa", "blu-sa", "CCVCV", 4, "blouse"],
  ["plato", "pla-to", "CCVCV", 4, "plate"],
  ["braso", "bra-so", "CCVCV", 4, "arm"],
  ["prito", "pri-to", "CCVCV", 4, "fried"],
  ["tren", "tren", "CCVC", 4, "train"],
  ["trak", "trak", "CCVC", 4, "truck"],
  ["krus", "krus", "CCVC", 4, "cross"],
  ["prutas", "pru-tas", "CCVCVC", 4, "fruit"],
  ["trapo", "tra-po", "CCVCV", 4, "rag"],
  ["plano", "pla-no", "CCVCV", 4, "plan"],
  ["drama", "dra-ma", "CCVCV", 4, "drama"],
  ["grado", "gra-do", "CCVCV", 4, "grade"],
  ["trabaho", "tra-ba-ho", "CCVCVCV", 4, "work"],
  ["prinsesa", "prin-se-sa", "CCVCCVCV", 4, "princess"],
  ["problema", "prob-le-ma", "CCVCCVCV", 4, "problem"],
  ["libro", "lib-ro", "CVCCCV", 4, "book"],
  ["sobre", "sob-re", "CVCCCV", 4, "envelope"],
  ["tainga", "ta-i-nga", "CVVCV(ng)", 4, "ear"],
  ["pinggan", "ping-gan", "CVCCVC(ng)", 4, "dish"],
  ["singkamas", "sing-ka-mas", "CVCCVCVC(ng)", 4, "jicama"],
  ["pangalan", "pa-nga-lan", "CVCVCVC(ng)", 4, "name"],
  ["pangako", "pa-nga-ko", "CVCVCV(ng)", 4, "promise"],
  ["pangarap", "pa-nga-rap", "CVCVCVC(ng)", 4, "dream"],
  ["tanghali", "tang-ha-li", "CVCCVCV(ng)", 4, "noon"],
  ["dyip", "dyip", "CCVC", 4, "jeepney"],
  ["gitara", "gi-ta-ra", "CVCVCV", 4, "guitar"],
  ["kwento", "kwen-to", "CCVCCV", 4, "story"],

  /* ── Level 5 — four or more syllables ─────────────────────────────────── */
  ["kalabasa", "ka-la-ba-sa", "CVCVCVCV", 5, "squash"],
  ["paaralan", "pa-a-ra-lan", "CVVCVCVC", 5, "school"],
  ["mahalaga", "ma-ha-la-ga", "CVCVCVCV", 5, "important"],
  ["karagatan", "ka-ra-ga-tan", "CVCVCVCVC", 5, "ocean"],
  ["kaibigan", "ka-i-bi-gan", "CVVCVCVC", 5, "friend"],
  ["matalino", "ma-ta-li-no", "CVCVCVCV", 5, "intelligent"],
  ["kalayaan", "ka-la-ya-an", "CVCVCVVC", 5, "freedom"],
  ["kasaysayan", "ka-say-sa-yan", "CVCVCCVCVC", 5, "history"],
  ["paruparo", "pa-ru-pa-ro", "CVCVCVCV", 5, "butterfly"],
  ["kalapati", "ka-la-pa-ti", "CVCVCVCV", 5, "dove"],
  ["pamilihan", "pa-mi-li-han", "CVCVCVCVC", 5, "market"],
  ["maliwanag", "ma-li-wa-nag", "CVCVCVCVC", 5, "bright"],
  ["kababayan", "ka-ba-ba-yan", "CVCVCVCVC", 5, "countryman"],
  ["kalusugan", "ka-lu-su-gan", "CVCVCVCVC", 5, "health"],
  ["himpapawid", "him-pa-pa-wid", "CVCCVCVCVC", 5, "sky"],
  ["talahiban", "ta-la-hi-ban", "CVCVCVCVC", 5, "grassland"],
  ["kasiyahan", "ka-si-ya-han", "CVCVCVCVC", 5, "celebration"],
  ["karunungan", "ka-ru-nu-ngan", "CVCVCVCVC(ng)", 5, "knowledge"],
  ["pangungusap", "pa-ngu-ngu-sap", "CVCVCVCVC(ng)", 5, "sentence"],
  ["tsinelas", "tsi-ne-las", "CCVCVCVC", 5, "slippers"],
  ["kwaderno", "kwa-der-no", "CCVCVCCV", 5, "notebook"],
  ["bisikleta", "bi-sik-le-ta", "CVCVCCVCV", 5, "bicycle"],
  ["alkansya", "al-kan-sya", "VCCVCCCV", 5, "coin bank"],
  ["kapatid", "ka-pa-tid", "CVCVCVC", 5, "sibling"],
  ["magulang", "ma-gu-lang", "CVCVCVC(ng)", 5, "parent"],
];

/**
 * Spellings the speech recogniser legitimately returns for a *correct* reading.
 * Loanwords and digraphs are the usual offenders: Whisper writes "krus" as
 * "cross" and "dyip" as "deep". Without these, a child who reads the word
 * perfectly would be scored as making an error. Compared exactly, so they can
 * never mask a genuine misreading.
 */
export const ASR_VARIANTS: Record<string, string> = {
  krus: "cross, kurs",
  dyip: "deep, jeep, dip, dape, dyp",
  tsinelas: "chinelas, sinelas, sinilas, sinalas, tsinelas",
  mangga: "manga",
  bulaklak: "bulaklaq, bulaklac",
  kotse: "kotche, coche",
  radyo: "radio",
  tren: "train",
  plato: "platto",
  bus: "boss, bas",
  trak: "truck",
  drama: "trama",
  grado: "grato",
  libro: "libru",
  sobre: "sobri",
  kwento: "cuento, kuwento",
  kwaderno: "cuaderno, kuwaderno",
  alkansya: "alkansiya, alcancia",
  bisikleta: "bicicleta",
  klase: "clase",
  blusa: "blusa, bluza",
  gitara: "guitara, guitarra",
  prinsesa: "princesa",
  problema: "problema, poblema",
};
